SELECT C.CLIENT_ID, C.SURNAME, CA.CLIENT_ACCOUNT_NUMBER,
AT.DESCRIPTION, CA.DISPLAY_BALANCE
FROM CLIENT C
JOIN CLIENT_ACCOUNT CA ON C.CLIENT_ID = CA.CLIENT_ID
JOIN ACCOUNT_TYPE AT ON AT.ACCOUNT_TYPE_CODE = CA.ACCOUNT_TYPE_CODE
JOIN (
SELECT C.CLIENT_ID ID, MAX(CA.DISPLAY_BALANCE) MAX_BALANCE
FROM CLIENT C
JOIN CLIENT_ACCOUNT CA ON C.CLIENT_ID = CA.CLIENT_ID
JOIN ACCOUNT_TYPE AT ON AT.ACCOUNT_TYPE_CODE = CA.ACCOUNT_TYPE_CODE
WHERE AT.TRANSACTIONAL  = TRUE
GROUP BY C.CLIENT_ID ) TABLE1
ON C.CLIENT_ID = TABLE1.ID
AND CA.DISPLAY_BALANCE = TABLE1.MAX_BALANCE
ORDER BY 1 DESC